name: pr_reviewers_ping

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
